// ---------------------------------------------------------------------------
// Signed Exchange Envelope — Phase 10, §10.6.
//
// Binds an attestation to a specific exchange with a specific peer.
// The envelope signature covers:
//   nonce ‖ peer_agent_id ‖ attestation_hash ‖ chain_root_hash ‖ timestamp
// (all fixed-width, no delimiters needed).
// ---------------------------------------------------------------------------

use ed25519_dalek::{Signer, SigningKey, Verifier, VerifyingKey};

use got_attest::serialise_for_signing;
use got_core::GeometricAttestation;

use crate::WireError;

/// Signed exchange envelope — wraps an attestation in exchange-specific bindings.
#[derive(Debug, Clone)]
pub struct ExchangeEnvelope {
    /// Random 32-byte nonce (generated by initiator, echoed by responder).
    pub nonce: [u8; 32],
    /// SHA-256 of the intended recipient's public key.
    pub peer_agent_id: [u8; 32],
    /// SHA-256 of the current attestation's `serialise_for_signing()` bytes.
    pub attestation_hash: [u8; 32],
    /// SHA-256 of chain[0]'s `serialise_for_signing()` bytes, or zeroes if no chain.
    pub chain_root_hash: [u8; 32],
    /// Unix UTC seconds when the envelope was created.
    pub timestamp: u64,
    /// Ed25519 signature over all fields above.
    pub signature: [u8; 64],
    /// Defence-in-depth: tracks whether `verify()` has been called successfully.
    /// Starts `false` from `from_bytes()` / `from_bytes_verified()`.
    /// Set to `true` only by a successful `verify()` call.
    /// `create()` also sets this to `true` (self-signed, implicitly verified).
    verified: bool,
}

/// Size of the signable portion: 32 + 32 + 32 + 32 + 8 = 136 bytes.
pub const SIGNABLE_SIZE: usize = 136;

/// Total serialised envelope size: 136 + 64 = 200 bytes.
pub const ENVELOPE_SIZE: usize = 200;

impl ExchangeEnvelope {
    /// Build the fixed-width byte array that is signed.
    pub fn signable_bytes(&self) -> [u8; SIGNABLE_SIZE] {
        let mut buf = [0u8; SIGNABLE_SIZE];
        buf[0..32].copy_from_slice(&self.nonce);
        buf[32..64].copy_from_slice(&self.peer_agent_id);
        buf[64..96].copy_from_slice(&self.attestation_hash);
        buf[96..128].copy_from_slice(&self.chain_root_hash);
        buf[128..136].copy_from_slice(&self.timestamp.to_le_bytes());
        buf
    }

    /// Create and sign an envelope.
    #[allow(clippy::too_many_arguments)]
    pub fn create(
        nonce: [u8; 32],
        peer_agent_id: [u8; 32],
        attestation: &GeometricAttestation,
        chain_anchor: Option<&GeometricAttestation>,
        timestamp: u64,
        signing_key: &SigningKey,
    ) -> Result<Self, WireError> {
        let attest_bytes = serialise_for_signing(attestation)?;
        let attestation_hash = got_core::sha256(&attest_bytes);

        let chain_root_hash = match chain_anchor {
            Some(anchor) => {
                let anchor_bytes = serialise_for_signing(anchor)?;
                got_core::sha256(&anchor_bytes)
            }
            None => [0u8; 32],
        };

        let mut envelope = Self {
            nonce,
            peer_agent_id,
            attestation_hash,
            chain_root_hash,
            timestamp,
            signature: [0u8; 64],
            verified: true, // self-signed → implicitly verified
        };

        let signable = envelope.signable_bytes();
        let sig = signing_key.sign(&signable);
        envelope.signature = sig.to_bytes();

        Ok(envelope)
    }

    /// Verify the envelope's signature and all bindings.
    ///
    /// * `expected_own_id` — our agent ID; must match `peer_agent_id`.
    /// * `expected_nonce` — for responses, the nonce we sent; `None` for requests.
    /// * `attestation` — the attestation payload; hash must match `attestation_hash`.
    /// * `chain_anchor` — first attestation in chain (if any); hash must match.
    /// * `signer_pk` — the sender's public key to verify the signature.
    /// * `now` — current Unix timestamp for freshness check.
    /// * `max_age_secs` — maximum allowed age of the envelope timestamp.
    #[allow(clippy::too_many_arguments)]
    pub fn verify(
        &self,
        expected_own_id: &[u8; 32],
        expected_nonce: Option<&[u8; 32]>,
        attestation: &GeometricAttestation,
        chain_anchor: Option<&GeometricAttestation>,
        signer_pk: &VerifyingKey,
        now: u64,
        max_age_secs: u64,
    ) -> Result<(), WireError> {
        // 1. Verify Ed25519 signature
        let signable = self.signable_bytes();
        let sig = ed25519_dalek::Signature::from_bytes(&self.signature);
        signer_pk
            .verify(&signable, &sig)
            .map_err(|_| WireError::EnvelopeSignatureInvalid)?;

        // 2. Check peer_agent_id matches our own ID
        if self.peer_agent_id != *expected_own_id {
            return Err(WireError::PeerIdMismatch {
                expected: hex_short(expected_own_id),
                got: hex_short(&self.peer_agent_id),
            });
        }

        // 3. Check nonce (for responses)
        if let Some(expected) = expected_nonce {
            if self.nonce != *expected {
                return Err(WireError::NonceMismatch);
            }
        }

        // 4. Check attestation hash
        let attest_bytes = serialise_for_signing(attestation)?;
        let actual_hash = got_core::sha256(&attest_bytes);
        if self.attestation_hash != actual_hash {
            return Err(WireError::AttestationHashMismatch);
        }

        // 5. Check chain root hash
        let expected_root = match chain_anchor {
            Some(anchor) => {
                let anchor_bytes = serialise_for_signing(anchor)?;
                got_core::sha256(&anchor_bytes)
            }
            None => [0u8; 32],
        };
        if self.chain_root_hash != expected_root {
            return Err(WireError::ChainRootHashMismatch);
        }

        // 6. Timestamp freshness — reject both too-old and future timestamps
        if self.timestamp > now {
            return Err(WireError::TimestampExpired {
                age_secs: 0,
                max_secs: max_age_secs,
            });
        }
        let age = now - self.timestamp;
        if age > max_age_secs {
            return Err(WireError::TimestampExpired {
                age_secs: age,
                max_secs: max_age_secs,
            });
        }

        Ok(())
    }

    /// Serialise the envelope to bytes (fixed 200-byte encoding).
    pub fn to_bytes(&self) -> [u8; ENVELOPE_SIZE] {
        let mut buf = [0u8; ENVELOPE_SIZE];
        buf[0..136].copy_from_slice(&self.signable_bytes());
        buf[136..200].copy_from_slice(&self.signature);
        buf
    }

    /// Deserialise an envelope from bytes.
    ///
    /// **Warning**: the returned envelope is *unverified*.  Callers MUST call
    /// [`verify()`](Self::verify) before trusting any field.  Prefer
    /// [`from_bytes_verified()`](Self::from_bytes_verified) for production use.
    pub fn from_bytes(data: &[u8; ENVELOPE_SIZE]) -> Self {
        let mut nonce = [0u8; 32];
        let mut peer_agent_id = [0u8; 32];
        let mut attestation_hash = [0u8; 32];
        let mut chain_root_hash = [0u8; 32];
        let mut ts_bytes = [0u8; 8];
        let mut signature = [0u8; 64];

        nonce.copy_from_slice(&data[0..32]);
        peer_agent_id.copy_from_slice(&data[32..64]);
        attestation_hash.copy_from_slice(&data[64..96]);
        chain_root_hash.copy_from_slice(&data[96..128]);
        ts_bytes.copy_from_slice(&data[128..136]);
        signature.copy_from_slice(&data[136..200]);

        Self {
            nonce,
            peer_agent_id,
            attestation_hash,
            chain_root_hash,
            timestamp: u64::from_le_bytes(ts_bytes),
            signature,
            verified: false,
        }
    }

    /// Deserialise **and** verify an envelope in a single step.
    ///
    /// This is the recommended entry-point for production code.  It
    /// combines [`from_bytes()`](Self::from_bytes) with
    /// [`verify()`](Self::verify) and marks the result as verified.
    #[allow(clippy::too_many_arguments)]
    pub fn from_bytes_verified(
        data: &[u8; ENVELOPE_SIZE],
        expected_own_id: &[u8; 32],
        expected_nonce: Option<&[u8; 32]>,
        attestation: &GeometricAttestation,
        chain_anchor: Option<&GeometricAttestation>,
        signer_pk: &VerifyingKey,
        now: u64,
        max_age_secs: u64,
    ) -> Result<Self, WireError> {
        let mut env = Self::from_bytes(data);
        env.verify(
            expected_own_id,
            expected_nonce,
            attestation,
            chain_anchor,
            signer_pk,
            now,
            max_age_secs,
        )?;
        env.verified = true;
        Ok(env)
    }

    /// Returns `true` if this envelope was produced by [`create()`](Self::create)
    /// or successfully passed through [`from_bytes_verified()`](Self::from_bytes_verified).
    pub fn is_verified(&self) -> bool {
        self.verified
    }
}

/// Short hex for error messages.
fn hex_short(bytes: &[u8; 32]) -> String {
    bytes[..4]
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect::<String>()
        + "..."
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::compute_agent_id as agent_id;
    use ed25519_dalek::SigningKey;
    use got_core::{GeometricAttestation, InnerProduct, Precision, SCHEMA_VERSION};

    fn test_key_a() -> SigningKey {
        SigningKey::from_bytes(&[0xAA; 32])
    }

    fn test_key_b() -> SigningKey {
        SigningKey::from_bytes(&[0xBB; 32])
    }

    fn make_attestation() -> GeometricAttestation {
        GeometricAttestation {
            schema_version: SCHEMA_VERSION,
            model_id: "test-model".to_string(),
            model_hash: Some([0x11; 32]),
            precision: Precision::Fp32,
            inner_product: InnerProduct::Causal,
            input_hash: [0x22; 32],
            timestamp: 1000,
            corpus_version: "cv1".to_string(),
            probe_version: "pv1".to_string(),
            layer_readings: vec![vec![0.5]],
            confidence: vec![0.9],
            coverage_flags: vec![false],
            divergence_flag: false,
            parent_attestation_hash: None,
            geometry_hash: None,
            geometry_drift: None,
            causal_scores: vec![],
            intervention_delta: None,
            causal_flag: None,
            sequence_number: 0,
            directional_drifts: vec![],
            probe_commitment: None,
            density_reading: None,
            curvature_reading: None,
            domain_scope_declaration: None,
            signature: [0u8; 64],
        }
    }

    #[test]
    fn envelope_create_and_verify_roundtrip() {
        let key_a = test_key_a();
        let key_b = test_key_b();
        let id_b = agent_id(&key_b.verifying_key());
        let attest = make_attestation();
        let nonce = [0x42; 32];
        let now = 5000u64;

        let env = ExchangeEnvelope::create(nonce, id_b, &attest, None, now, &key_a).unwrap();

        // B verifies
        env.verify(
            &id_b,
            None, // request — no expected nonce from B's side
            &attest,
            None,
            &key_a.verifying_key(),
            now + 10,
            300,
        )
        .unwrap();
    }

    #[test]
    fn envelope_with_chain_anchor() {
        let key_a = test_key_a();
        let key_b = test_key_b();
        let id_b = agent_id(&key_b.verifying_key());
        let attest = make_attestation();
        let anchor = make_attestation(); // same for simplicity
        let nonce = [0x42; 32];
        let now = 5000u64;

        let env =
            ExchangeEnvelope::create(nonce, id_b, &attest, Some(&anchor), now, &key_a).unwrap();

        env.verify(
            &id_b,
            None,
            &attest,
            Some(&anchor),
            &key_a.verifying_key(),
            now + 5,
            300,
        )
        .unwrap();
    }

    #[test]
    fn envelope_wrong_nonce_rejected() {
        let key_a = test_key_a();
        let key_b = test_key_b();
        let id_a = agent_id(&key_a.verifying_key());
        let attest = make_attestation();
        let nonce = [0x42; 32];
        let wrong_nonce = [0x99; 32];
        let now = 5000u64;

        // B creates response echoing nonce
        let env = ExchangeEnvelope::create(nonce, id_a, &attest, None, now, &key_b).unwrap();

        // A checks with different expected nonce
        let err = env
            .verify(
                &id_a,
                Some(&wrong_nonce),
                &attest,
                None,
                &key_b.verifying_key(),
                now + 5,
                300,
            )
            .unwrap_err();
        assert!(matches!(err, WireError::NonceMismatch));
    }

    #[test]
    fn envelope_wrong_peer_id_rejected() {
        let key_a = test_key_a();
        let key_b = test_key_b();
        let id_b = agent_id(&key_b.verifying_key());
        let wrong_id = [0xFF; 32];
        let attest = make_attestation();
        let now = 5000u64;

        let env = ExchangeEnvelope::create([0x42; 32], id_b, &attest, None, now, &key_a).unwrap();

        let err = env
            .verify(
                &wrong_id,
                None,
                &attest,
                None,
                &key_a.verifying_key(),
                now + 5,
                300,
            )
            .unwrap_err();
        assert!(matches!(err, WireError::PeerIdMismatch { .. }));
    }

    #[test]
    fn envelope_tampered_attestation_rejected() {
        let key_a = test_key_a();
        let key_b = test_key_b();
        let id_b = agent_id(&key_b.verifying_key());
        let attest = make_attestation();
        let now = 5000u64;

        let env = ExchangeEnvelope::create([0x42; 32], id_b, &attest, None, now, &key_a).unwrap();

        // Tamper the attestation
        let mut tampered = make_attestation();
        tampered.timestamp = 9999;

        let err = env
            .verify(
                &id_b,
                None,
                &tampered,
                None,
                &key_a.verifying_key(),
                now + 5,
                300,
            )
            .unwrap_err();
        assert!(matches!(err, WireError::AttestationHashMismatch));
    }

    #[test]
    fn envelope_expired_timestamp_rejected() {
        let key_a = test_key_a();
        let key_b = test_key_b();
        let id_b = agent_id(&key_b.verifying_key());
        let attest = make_attestation();
        let now = 5000u64;

        let env = ExchangeEnvelope::create([0x42; 32], id_b, &attest, None, now, &key_a).unwrap();

        let err = env
            .verify(
                &id_b,
                None,
                &attest,
                None,
                &key_a.verifying_key(),
                now + 1000, // way too late
                300,
            )
            .unwrap_err();
        assert!(matches!(err, WireError::TimestampExpired { .. }));
    }

    #[test]
    fn envelope_forged_signature_rejected() {
        let key_a = test_key_a();
        let key_b = test_key_b();
        let id_b = agent_id(&key_b.verifying_key());
        let attest = make_attestation();
        let now = 5000u64;

        let mut env =
            ExchangeEnvelope::create([0x42; 32], id_b, &attest, None, now, &key_a).unwrap();

        // Forge: flip a byte in the signature
        env.signature[0] ^= 0xFF;

        let err = env
            .verify(
                &id_b,
                None,
                &attest,
                None,
                &key_a.verifying_key(),
                now + 5,
                300,
            )
            .unwrap_err();
        assert!(matches!(err, WireError::EnvelopeSignatureInvalid));
    }

    #[test]
    fn envelope_bytes_roundtrip() {
        let key_a = test_key_a();
        let key_b = test_key_b();
        let id_b = agent_id(&key_b.verifying_key());
        let attest = make_attestation();

        let env = ExchangeEnvelope::create([0x42; 32], id_b, &attest, None, 5000, &key_a).unwrap();

        let bytes = env.to_bytes();
        let restored = ExchangeEnvelope::from_bytes(&bytes);

        assert_eq!(env.nonce, restored.nonce);
        assert_eq!(env.peer_agent_id, restored.peer_agent_id);
        assert_eq!(env.attestation_hash, restored.attestation_hash);
        assert_eq!(env.chain_root_hash, restored.chain_root_hash);
        assert_eq!(env.timestamp, restored.timestamp);
        assert_eq!(env.signature, restored.signature);
    }

    #[test]
    fn agent_id_is_sha256_of_pubkey() {
        let key = test_key_a();
        let pk = key.verifying_key();
        let id = agent_id(&pk);
        let expected = got_core::sha256(pk.as_bytes());
        assert_eq!(id, expected);
    }

    #[test]
    fn envelope_chain_root_mismatch_rejected() {
        let key_a = test_key_a();
        let key_b = test_key_b();
        let id_b = agent_id(&key_b.verifying_key());
        let attest = make_attestation();
        let anchor = make_attestation();
        let now = 5000u64;

        // Create with chain anchor
        let env = ExchangeEnvelope::create([0x42; 32], id_b, &attest, Some(&anchor), now, &key_a)
            .unwrap();

        // Verify with no chain anchor → hash mismatch
        let err = env
            .verify(
                &id_b,
                None,
                &attest,
                None,
                &key_a.verifying_key(),
                now + 5,
                300,
            )
            .unwrap_err();
        assert!(matches!(err, WireError::ChainRootHashMismatch));
    }

    // -----------------------------------------------------------------------
    // Security regression tests (Issue 30 / S-9)
    // -----------------------------------------------------------------------

    /// Issue #30 (S-9): `from_bytes()` returns an unverified envelope
    /// (`is_verified() == false`).  `from_bytes_verified()` atomically
    /// parses and verifies — rejecting bad signatures and returning a
    /// verified envelope on success.
    #[test]
    fn sec_envelope_from_bytes_verified_gate() {
        let key_a = test_key_a();
        let key_b = test_key_b();
        let id_b = agent_id(&key_b.verifying_key());
        let attest = make_attestation();
        let now = 5000u64;

        // --- 1. create() produces a verified envelope ---
        let env = ExchangeEnvelope::create([0x42; 32], id_b, &attest, None, now, &key_a).unwrap();
        assert!(
            env.is_verified(),
            "create() must produce a verified envelope"
        );

        let bytes = env.to_bytes();

        // --- 2. from_bytes() produces an UN-verified envelope ---
        let raw = ExchangeEnvelope::from_bytes(&bytes);
        assert!(
            !raw.is_verified(),
            "from_bytes() must return an unverified envelope"
        );

        // --- 3. from_bytes_verified() rejects garbage signature ---
        let mut bad = bytes;
        bad[136] ^= 0xFF; // flip a signature byte
        let err = ExchangeEnvelope::from_bytes_verified(
            &bad,
            &id_b,
            None,
            &attest,
            None,
            &key_a.verifying_key(),
            now + 5,
            300,
        );
        assert!(
            err.is_err(),
            "from_bytes_verified must reject a tampered signature"
        );

        // --- 4. from_bytes_verified() accepts a valid envelope ---
        let verified = ExchangeEnvelope::from_bytes_verified(
            &bytes,
            &id_b,
            None,
            &attest,
            None,
            &key_a.verifying_key(),
            now + 5,
            300,
        )
        .expect("from_bytes_verified must accept a valid envelope");
        assert!(
            verified.is_verified(),
            "from_bytes_verified must return a verified envelope"
        );
        assert_eq!(verified.nonce, [0x42; 32]);
    }
}
